opt_in_rules:
  - empty_count
  - contains_over_first_not_nil
  - fatal_error_message
  - first_where
  - number_separator
  - operator_usage_whitespace
  - toggle_bool
  - convenience_type
  - empty_string
  - fallthrough
  - legacy_random
  - multiline_function_chains
  - multiline_parameters
  - pattern_matching_keywords
  - private_outlet
  - private_action
  - redundant_type_annotation
  - sorted_first_last
  - strict_fileprivate
  - syntactic_sugar
  - modifier_order
  - yoda_condition
  - unused_declaration


disabled_rules:
- convenience_type
- multiple_closures_with_trailing_closure
- trailing_comma
- type_name
- no_space_in_method_call
- cyclomatic_complexity
- file_length
- todo
- function_parameter_count
- inclusive_language
- orphaned_doc_comment

analyzer_rules:
- unused_declaration
- unused_import

# paths to include during linting. `--path` is ignored if present.
included:
- Intree
- IntreeTests

reporter: "xcode"



####
# Individual Rule Configuration (See: https://realm.github.io/SwiftLint/rule-directory.html)
####

colon:
  flexible_right_spacing: true

vertical_whitespace:
  max_empty_lines: 3

function_body_length:
  warning: 50
  error: 100

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  warning: 130
  error: 200

type_body_length:
  warning: 300
  error: 500

large_tuple:
  warning: 4
  error: 6

identifier_name:
  excluded:
    - id
    - up
  validates_start_with_lowercase: off
  max_length: 50

nesting:
  type_level:
    warning: 4

number_separator:
  minimum_length: 5

generic_type_name:
  max_length: 30
