name: Danger
 
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited]
    branches: ["master", "develop", "feature/*", "bugfix/*"]
 
env:
  DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
 
jobs:
  main:
    name: Review, Lint, Verify
    runs-on: macOS-15
    steps:
      - name: git checkout
        uses: actions/checkout@v3
  
      - name: Select Xcode
        run: |
          xcodebuild -version
          ls -nt /Applications/ | grep "Xcode*"
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
          xcodebuild -version
 
      - name: Install swiftlint
        run:  brew install swiftlint
 
      - name: Install danger-js
        run: brew install danger/tap/danger-js
        shell: bash
 
      - name: danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: swift run danger-swift ci
