name: Danger
 
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited]
    branches: ["master", "develop", "feature/*", "bugfix/*"]
 
env:
  DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
 
jobs:
  main:
    name: Review, Lint, Verify
    runs-on: macos-14
    steps:
      - name: git checkout
        uses: actions/checkout@v3
 
      # - name: ruby versions
      #   run: |
      #     ruby --version
      #     gem --version
      #     bundler --version
 
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.3.app/Contents/Developer'
 
      # - name: ruby setup
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 2.7
      #     bundler-cache: true
 
      - name: Install swiftlint
        run:  brew install swiftlint
 
      - name: Install danger
        run: brew install danger/tap/danger-swift
        shell: bash
 
      - name: danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: danger-swift ci
