name: Danger
 
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited]
    branches: ["master", "develop", "feature/*", "bugfix/*"]
 
jobs:
  main:
    name: Review, Lint, Verify
    runs-on: macOS-15
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 16.0
      - run: xcodebuild -version
#      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install danger-js
        run: brew install danger/tap/danger-js

      - name: danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./Danger
        run: swift run danger-swift ci --cwd ..

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
