name: Danger
 
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited]
    branches: ["master", "develop", "feature/*", "bugfix/*"]
 
jobs:
  main:
    name: Review, Lint, Verify
    runs-on: macOS-15
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
        for commit in $(git rev-list ${{ github.base_ref }}..${{ github.head_ref }}); do
            git checkout $commit
            echo "run test"
        done
  
      - name: Select Xcode
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 16.0
 
      - name: Install swiftlint
        run:  brew install swiftlint
 
      - name: Install danger-js
        run: brew install danger/tap/danger-js
        shell: bash
 
      - name: danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: swift run danger-swift ci
